package com.speak2wake.core.designsystem.strings

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    // Home
    val appName: String,
    val settings: String,
    val addAlarm: String,
    val noAlarmsYet: String,
    val tapToCreate: String,
    val createAlarm: String,
    val testAlarm: String,
    val delete: String,
    // Create/Edit
    val newAlarm: String,
    val editAlarm: String,
    val hour: String,
    val minute: String,
    val labelOptional: String,
    val repeat: String,
    val snooze: String,
    val duration: String,
    val min: String,
    val alarmSound: String,
    val change: String,
    val reset: String,
    val vibrate: String,
    val voiceChallenge: String,
    val challengeLanguageLabel: String,
    val germanChallenge: String,
    val vietnameseChallenge: String,
    val vocabularyLevel: String,
    val alwaysPronounce: String,
    val wordCount: String,
    val wordCountWords: String, // "words"
    val saveAlarm: String,
    val updateAlarm: String,
    val selectAlarmSound: String,
    val back: String,
    // Ring
    val startChallenge: String,
    val dismissAlarm: String,
    val snoozeFormat: String, // "Snooze %dm"
    // Challenge
    val wordProgressFormat: String, // "Word %d / %d"
    val attemptFormat: String, // "Attempt %d / %d"
    val listen: String,
    val changeWord: String,
    val tapMicToSpeak: String,
    val listeningSpeak: String,
    val scoring: String,
    val cantSpeakTypeFormat: String, // "Can't speak? Type \"%s\":"
    val typeInGerman: String,
    val typeInVietnamese: String,
    val submit: String,
    val alarmDismissedMsg: String,
    val goodMorning: String,
    // Settings
    val settingsTitle: String,
    val alarmDefaults: String,
    val snoozeDuration: String,
    val defaultForNew: String,
    val vibrateWhenRings: String,
    val requirePronunciation: String,
    val vocabulary: String,
    val totalWords: String,
    val mastered: String,
    val about: String,
    val version: String,
    val app: String,
    val language: String,
    val appLanguage: String,
    val vietnamese: String,
    val english: String,
)

val EnglishStrings = AppStrings(
    // Home
    appName = "Speak2Wake",
    settings = "Settings",
    addAlarm = "Add Alarm",
    noAlarmsYet = "No alarms yet",
    tapToCreate = "Tap + to create your first alarm",
    createAlarm = "Create Alarm",
    testAlarm = "Test Alarm",
    delete = "Delete",
    // Create/Edit
    newAlarm = "New Alarm",
    editAlarm = "Edit Alarm",
    hour = "Hour",
    minute = "Minute",
    labelOptional = "Label (optional)",
    repeat = "Repeat",
    snooze = "Snooze",
    duration = "Duration",
    min = "min",
    alarmSound = "Alarm Sound",
    change = "Change",
    reset = "Reset",
    vibrate = "Vibrate",
    voiceChallenge = "Voice Challenge",
    challengeLanguageLabel = "Challenge Language",
    germanChallenge = "German",
    vietnameseChallenge = "Vietnamese",
    vocabularyLevel = "Vocabulary Level",
    alwaysPronounce = "Auto-pronounce word",
    wordCount = "Number of words",
    wordCountWords = "words",
    saveAlarm = "Save Alarm",
    updateAlarm = "Update Alarm",
    selectAlarmSound = "Select Alarm Sound",
    back = "Back",
    // Ring
    startChallenge = "Start Challenge",
    dismissAlarm = "Dismiss Alarm",
    snoozeFormat = "Snooze %dm",
    // Challenge
    wordProgressFormat = "Word %d / %d",
    attemptFormat = "Attempt %d / %d",
    listen = "Listen",
    changeWord = "Change Word",
    tapMicToSpeak = "Tap mic to speak",
    listeningSpeak = "Listening... speak now",
    scoring = "Scoring...",
    cantSpeakTypeFormat = "Can't speak? Type \"%s\":",
    typeInGerman = "Type in German...",
    typeInVietnamese = "Type in Vietnamese...",
    submit = "Submit",
    alarmDismissedMsg = "Alarm dismissed!",
    goodMorning = "Good morning!",
    // Settings
    settingsTitle = "Settings",
    alarmDefaults = "Alarm Defaults",
    snoozeDuration = "Snooze Duration",
    defaultForNew = "Default for new alarms",
    vibrateWhenRings = "Vibrate when alarm rings",
    requirePronunciation = "Require pronunciation to dismiss",
    vocabulary = "Vocabulary",
    totalWords = "Total Words",
    mastered = "Mastered",
    about = "About",
    version = "Version",
    app = "App",
    language = "Language",
    appLanguage = "App Language",
    vietnamese = "Tiếng Việt",
    english = "English",
)

val VietnameseStrings = AppStrings(
    // Home
    appName = "Speak2Wake",
    settings = "Cài đặt",
    addAlarm = "Thêm báo thức",
    noAlarmsYet = "Chưa có báo thức",
    tapToCreate = "Nhấn + để tạo báo thức đầu tiên",
    createAlarm = "Tạo báo thức",
    testAlarm = "Thử báo thức",
    delete = "Xóa",
    // Create/Edit
    newAlarm = "Báo thức mới",
    editAlarm = "Chỉnh sửa",
    hour = "Giờ",
    minute = "Phút",
    labelOptional = "Nhãn (tùy chọn)",
    repeat = "Lặp lại",
    snooze = "Báo lại",
    duration = "Thời lượng",
    min = "phút",
    alarmSound = "Nhạc báo thức",
    change = "Đổi",
    reset = "Mặc định",
    vibrate = "Rung",
    voiceChallenge = "Thử thách phát âm",
    challengeLanguageLabel = "Ngôn ngữ thử thách",
    germanChallenge = "Tiếng Đức",
    vietnameseChallenge = "Tiếng Việt",
    vocabularyLevel = "Trình độ từ vựng",
    alwaysPronounce = "Luôn phát âm mẫu",
    wordCount = "Số từ cần đọc",
    wordCountWords = "từ",
    saveAlarm = "Lưu báo thức",
    updateAlarm = "Cập nhật",
    selectAlarmSound = "Chọn nhạc báo thức",
    back = "Quay lại",
    // Ring
    startChallenge = "Bắt đầu thử thách",
    dismissAlarm = "Tắt báo thức",
    snoozeFormat = "Báo lại %d phút",
    // Challenge
    wordProgressFormat = "Từ %d / %d",
    attemptFormat = "Lần thử %d / %d",
    listen = "Nghe",
    changeWord = "Đổi từ",
    tapMicToSpeak = "Nhấn mic để nói",
    listeningSpeak = "Đang nghe... hãy nói",
    scoring = "Đang chấm điểm...",
    cantSpeakTypeFormat = "Không nói được? Gõ \"%s\":",
    typeInGerman = "Gõ bằng tiếng Đức...",
    typeInVietnamese = "Gõ bằng tiếng Việt...",
    submit = "Gửi",
    alarmDismissedMsg = "Đã tắt báo thức!",
    goodMorning = "Chào buổi sáng!",
    // Settings
    settingsTitle = "Cài đặt",
    alarmDefaults = "Mặc định báo thức",
    snoozeDuration = "Thời gian báo lại",
    defaultForNew = "Mặc định cho báo thức mới",
    vibrateWhenRings = "Rung khi báo thức kêu",
    requirePronunciation = "Yêu cầu phát âm để tắt",
    vocabulary = "Từ vựng",
    totalWords = "Tổng số từ",
    mastered = "Đã thuộc",
    about = "Giới thiệu",
    version = "Phiên bản",
    app = "Ứng dụng",
    language = "Ngôn ngữ",
    appLanguage = "Ngôn ngữ ứng dụng",
    vietnamese = "Tiếng Việt",
    english = "English",
)

val LocalStrings = staticCompositionLocalOf { EnglishStrings }
